theme: jekyll-theme-minimal
title: Hayes et al. 2022 Nature
logo: "logo2.jpg"
description: Hayes LN, An K, Carloni E, Li F, Vincent E, Trippaers C, Paranjpe M, DÃ¶len G, Goff LA, Ramos A, Kano S, Sawa A. Prenatal immune stress blunts microglia reactivity, impairing neurocircuitry
